# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CQwBGPzl4POm85sw5HfzlFDW5miETtDX
"""

import numpy as np
import pandas as pd

pip install matplotlib

import matplotlib.pyplot as plt
import seaborn as sns

train=pd.read_csv('/content/train_LZdllcl.csv')

train.head()

train.shape

train.info()

train=pd.get_dummies(train,dtype=int)

train.head()

train.isna().sum()

plt.hist(train['previous_year_rating'])
plt.show()

train['previous_year_rating']=train['previous_year_rating'].fillna(train['previous_year_rating'].median())

train['previous_year_rating'].isna().sum()

test=pd.read_csv('/content/test_2umaH9m.csv')

test.head()

test.shape

test.info()

test.columns

test.isna().sum()

test['previous_year_rating']=test['previous_year_rating'].fillna(test['previous_year_rating'].median())

test['education']=test['education'].fillna(test['education'].mode()[0])

test[['previous_year_rating','education']].isna().sum()

test=pd.get_dummies(test,dtype=int)

x_train=train.drop('is_promoted',axis=1)
y_train=train['is_promoted']

from sklearn.preprocessing import PolynomialFeatures
poly_fr=PolynomialFeatures(degree=2)
x_poly_train=poly_fr.fit_transform(x_train)

from sklearn.linear_model import LinearRegression
lr=LinearRegression()
model=lr.fit(x_poly_train,y_train)

test_poly=poly_fr.fit_transform(test)

predictions=model.predict(test_poly)

predictions

predict=pd.DataFrame(predictions)

predict

analysis=pd.DataFrame(predict)

analysis

pip install IPython

import IPython

pip install colab-convert

colab-convert Untitled9.ipy